version: '3.8'
services:
  shop_fe_local:
    image: caleamare/shop_fe_local:v1
    container_name: shop_fe_local
    build:
      context: .
    ports:
      - '4200:80'
    networks:
      - shop_fe_local
networks:
  shop_fe_local:
    driver: bridge
    name: shop_fe_local
